name: Deploy Network Stack

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file templates/network-stack-infra.yaml \
            --stack-name network-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ca-central-1
